image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "23"
  ANDROID_BUILD_TOOLS: "23.0.1"
  ANDROID_SDK_TOOLS: "24"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --no-clobber --quiet --output-document=android-sdk-${ANDROID_SDK_TOOLS}.tgz https://dl.google.com/android/android-sdk_r${ANDROID_SDK_TOOLS}-linux.tgz || true
  - tar --extract --gzip --file=android-sdk-${ANDROID_SDK_TOOLS}.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter android-${ANDROID_COMPILE_SDK}
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS}
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter extra-google-google_play_services
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle    
  - mkdir -p $ANDROID_HOME/licenses/ \
    && echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - android-sdk-${ANDROID_SDK_TOOLS}.tgz

stages:
  - build

build:
  when: manual
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - org.fox.ttrss/build/outputs/apk/*.apk

